import { useEffect, useMemo, useState } from "react";
import { Pulse, ArrowsClockwise, ChartLineUp, Check, Database, DownloadSimple, FileText, GearSix, Info, Play, SlidersHorizontal, Strategy, TrendUp, UsersThree, X } from "@phosphor-icons/react";
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const API = import.meta.env.VITE_API_BASE || "http://127.0.0.1:8000/api";
const initialSettings = {
  symbols: ["600519.SH", "000333.SZ", "600036.SH"], start_date: "2018-01-01", end_date: "2024-05-20",
  initial_cash: 1000000, commission_rate: 0.00025, min_commission: 5, stamp_duty_rate: 0.0005,
  transfer_fee_rate: 0.00001, slippage_rate: 0.0002, max_position: 0.95, lot_size: 100,
  benchmark: "000300.SH", frequency: "1d",
  strategy: { name: "均线多头策略", buy_logic: "all", sell_logic: "any",
    buy_conditions: [{ indicator: "ma_cross", operator: "cross_above", left: 20, right: 60, threshold: 50 }],
    sell_conditions: [{ indicator: "ma_cross", operator: "cross_below", left: 20, right: 60, threshold: 50 }],
  },
};
const navItems = [["数据中心", Database], ["策略研究", Strategy], ["回测中心", ArrowsClockwise], ["因子分析", ChartLineUp], ["组合管理", UsersThree], ["结果分析", TrendUp], ["报告管理", FileText]];
const steps = ["选择数据", "配置策略", "设置成本", "运行回测", "分析结果"];
const formatPercent = (value, digits = 2) => `${(Number(value || 0) * 100).toFixed(digits)}%`;
const formatMoney = (value) => Number(value || 0).toLocaleString("zh-CN", { maximumFractionDigits: 0 });

function Metric({ label, value, tone }) { return <div className="metric"><span>{label}</span><strong className={tone || ""}>{value}</strong></div>; }
function ChartTooltip({ active, payload, label }) {
  if (!active || !payload?.length) return null;
  return <div className="chart-tooltip"><span>{label}</span>{payload.map((item) => <b key={item.dataKey} style={{ color: item.color }}>{item.name} {formatPercent(item.value)}</b>)}</div>;
}
function SettingRow({ label, children }) { return <label className="setting-row"><span>{label}</span>{children}</label>; }
function RateInput({ label, value, onChange, note }) {
  return <SettingRow label={label}><div className="rate-control"><div className="input-suffix"><input type="number" step="0.001" value={(value * 100).toFixed(3)} onChange={(event) => onChange(Number(event.target.value) / 100)} /><span>%</span></div><small>{note}</small></div></SettingRow>;
}

function SettingsDrawer({ settings, setSettings, onRun, onCancel, running, progress, close }) {
  const update = (field, value) => setSettings((current) => ({ ...current, [field]: value }));
  return <aside className="settings-drawer">
    <div className="drawer-title"><div><b>A 股回测设置</b><span>沪深 A 股 · 日线</span></div><button className="icon-button" onClick={close} aria-label="关闭"><X size={18} /></button></div>
    <section><h3>基础规则</h3><SettingRow label="市场范围"><span className="static-value">沪深 A 股</span></SettingRow><SettingRow label="交易规则"><span className="static-value">T+1</span></SettingRow><SettingRow label="数据频率"><select value={settings.frequency} disabled><option value="1d">日线（当前）</option></select></SettingRow><small className="hint">分钟线架构已预留，将在后续版本开放。</small></section>
    <section><h3>资金与仓位</h3><SettingRow label="初始资金"><input type="number" value={settings.initial_cash} onChange={(event) => update("initial_cash", Number(event.target.value))} /></SettingRow><SettingRow label="最大仓位"><div className="input-suffix"><input type="number" value={settings.max_position * 100} onChange={(event) => update("max_position", Number(event.target.value) / 100)} /><span>%</span></div></SettingRow></section>
    <section><h3>交易成本（双边）</h3><RateInput label="佣金费率" value={settings.commission_rate} onChange={(value) => update("commission_rate", value)} note={`最低 ${settings.min_commission} 元`} /><RateInput label="印花税率" value={settings.stamp_duty_rate} onChange={(value) => update("stamp_duty_rate", value)} note="仅卖出收取" /><RateInput label="滑点（成交价）" value={settings.slippage_rate} onChange={(value) => update("slippage_rate", value)} note="按成交价比例" /><RateInput label="过户费率" value={settings.transfer_fee_rate} onChange={(value) => update("transfer_fee_rate", value)} note="规则可版本化" /></section>
    <section><h3>数据设置</h3><SettingRow label="数据来源"><span className="static-value">AkShare + CSV</span></SettingRow><SettingRow label="复权方式"><span className="static-value">前复权信号</span></SettingRow><small className="hint">撮合始终使用未复权真实价格。</small></section>
    <div className="task-actions">{running && <button className="ghost" onClick={onCancel}>取消</button>}<button className="primary run-button" onClick={onRun} disabled={running}>{running ? <Pulse className="spin" size={18} /> : <Play weight="fill" size={18} />}{running ? `回测中 ${Math.round(progress * 100)}%` : "运行回测"}</button></div>
  </aside>;
}

function RuleNode({ title, tone, condition, onChange }) {
  return <div className={`rule-node ${tone}`}><b>{title}</b><span>短期均线</span><input type="number" value={condition.left} onChange={(event) => onChange("left", event.target.value)} /><span>{tone === "green" ? "上穿" : "下穿"}长期均线</span><input type="number" value={condition.right} onChange={(event) => onChange("right", event.target.value)} /></div>;
}
function StrategyModal({ settings, setSettings, onSave, saving, versionInfo, close }) {
  const strategy = settings.strategy;
  const updateCondition = (kind, key, value) => setSettings((current) => ({ ...current, strategy: { ...current.strategy, [kind]: current.strategy[kind].map((condition, index) => index === 0 ? { ...condition, [key]: Number(value) } : condition) } }));
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><div className="strategy-modal">
    <div className="modal-head"><div><span className="eyebrow">可视化策略</span><h2>配置「{strategy.name}」</h2><p>使用自然语言式条件组合，无需编写代码。{versionInfo ? ` 当前 ${versionInfo}` : " 尚未保存版本"}</p></div><button className="icon-button" onClick={close}><X size={20} /></button></div>
    <div className="rule-flow"><div className="rule-node source"><Database size={21} /><b>股票池</b><span>沪深 A 股 · {settings.symbols.length} 只</span></div><div className="connector" /><RuleNode title="买入条件" tone="green" condition={strategy.buy_conditions[0]} onChange={(key, value) => updateCondition("buy_conditions", key, value)} /><div className="connector" /><RuleNode title="卖出条件" tone="red" condition={strategy.sell_conditions[0]} onChange={(key, value) => updateCondition("sell_conditions", key, value)} /><div className="connector" /><div className="rule-node risk"><SlidersHorizontal size={21} /><b>仓位管理</b><span>最大仓位 {settings.max_position * 100}%</span></div></div>
    <div className="validation-row"><span><Check size={17} weight="bold" />规则检查通过</span><span>信号在收盘后产生</span><span>下一交易日开盘成交</span><span>T+1 可卖</span></div>
    <div className="modal-actions"><button className="ghost" onClick={close}>取消</button><button className="primary" onClick={onSave} disabled={saving}><Check size={18} />{saving ? "保存中…" : "保存新版本"}</button></div>
  </div></div>;
}

function DataDrawer({ settings, setSettings, securities, source, datasets, onImport, importing, close }) {
  const toggle = (symbol) => setSettings((current) => ({ ...current, symbols: current.symbols.includes(symbol) ? current.symbols.filter((item) => item !== symbol) : [...current.symbols, symbol] }));
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><div className="data-modal"><div className="modal-head"><div><span className="eyebrow">数据中心</span><h2>选择回测股票池</h2><p>{source?.message || "正在检查本地数据源"}</p></div><label className="csv-upload"><input type="file" accept=".csv,text/csv" onChange={onImport} disabled={importing} />{importing ? "正在校验…" : "导入 CSV"}</label><button className="icon-button" onClick={close}><X size={20} /></button></div><div className="security-list">{securities.map((item) => <button key={item.symbol} className={settings.symbols.includes(item.symbol) ? "selected" : ""} onClick={() => toggle(item.symbol)}><span><b>{item.name}</b><small>{item.symbol}</small></span>{settings.symbols.includes(item.symbol) && <Check size={18} weight="bold" />}</button>)}</div>{datasets.length > 0 && <div className="dataset-strip"><b>已导入数据集</b>{datasets.slice(0, 3).map((dataset) => <span key={dataset.id}>{dataset.name} · {dataset.symbol_count} 标的 · {dataset.row_count} 行</span>)}</div>}<div className="modal-actions"><span className="selection-count">已选择 {settings.symbols.length} 只股票</span><button className="primary" disabled={!settings.symbols.length} onClick={close}>确认股票池</button></div></div></div>;
}

function App() {
  const [settings, setSettings] = useState(initialSettings);
  const [result, setResult] = useState(null); const [running, setRunning] = useState(false); const [progress, setProgress] = useState(0); const [currentTaskId, setCurrentTaskId] = useState(null);
  const [drawer, setDrawer] = useState("settings"); const [securities, setSecurities] = useState([]);
  const [source, setSource] = useState(null); const [notice, setNotice] = useState(""); const [datasets, setDatasets] = useState([]); const [importing, setImporting] = useState(false); const [strategyRecord, setStrategyRecord] = useState(null); const [savingStrategy, setSavingStrategy] = useState(false);
  const runBacktest = async (candidateSignal) => { const signal = candidateSignal?.constructor?.name === "AbortSignal" ? candidateSignal : undefined; setRunning(true); setProgress(0); setNotice(""); try { const createResponse = await fetch(`${API}/backtests`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings), signal }); if (!createResponse.ok) throw new Error((await createResponse.json()).detail || "无法创建回测任务"); const task = await createResponse.json(); setCurrentTaskId(task.id); while (true) { const statusResponse = await fetch(`${API}/backtests/${task.id}`, { signal }); if (!statusResponse.ok) throw new Error("无法读取回测任务状态"); const status = await statusResponse.json(); setProgress(status.progress || 0); if (status.status === "completed") { const resultResponse = await fetch(`${API}/backtests/${task.id}/result`, { signal }); if (!resultResponse.ok) throw new Error("无法读取回测结果"); setResult(await resultResponse.json()); setNotice("回测已完成，结果已持久化"); break; } if (status.status === "failed" || status.status === "cancelled") throw new Error(status.error || `任务状态: ${status.status}`); await new Promise((resolve) => setTimeout(resolve, 180)); } } catch (error) { if (error.name !== "AbortError") setNotice(`回测未完成：${error.message}`); } finally { if (!signal?.aborted) { setRunning(false); setCurrentTaskId(null); } } };
  const cancelBacktest = async () => { if (!currentTaskId) return; try { await fetch(`${API}/backtests/${currentTaskId}/cancel`, { method: "POST" }); setNotice("正在取消回测任务…"); } catch (error) { setNotice(`取消失败：${error.message}`); } };
  const importCsv = async (event) => { const file = event.target.files?.[0]; if (!file) return; setImporting(true); try { const response = await fetch(`${API}/datasets/csv`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: file.name.replace(/\.csv$/i, ""), csv_text: await file.text() }) }); if (!response.ok) throw new Error((await response.json()).detail || "CSV 校验失败"); const dataset = await response.json(); setDatasets((current) => [dataset, ...current.filter((item) => item.id !== dataset.id)]); setNotice(dataset.duplicate ? "该数据集已存在，已显示原记录" : `数据集已导入：${dataset.summary.row_count} 行`); } catch (error) { setNotice(`导入失败：${error.message}`); } finally { setImporting(false); event.target.value = ""; } };
  const saveStrategy = async () => { setSavingStrategy(true); try { let response; if (strategyRecord) { response = await fetch(`${API}/strategies/${strategyRecord.id}/versions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ definition: settings.strategy, note: "从可视化编辑器保存" }) }); } else { response = await fetch(`${API}/strategies`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project_id: "default", name: settings.strategy.name, definition: settings.strategy }) }); } if (!response.ok) throw new Error((await response.json()).detail || "策略保存失败"); const saved = await response.json(); if (strategyRecord) { setStrategyRecord((current) => ({ ...current, latest_version: saved })); setSettings((current) => ({ ...current, project_id: "default", strategy_id: strategyRecord.id, strategy_version_id: saved.id })); setNotice(`策略版本 v${saved.version} 已保存`); } else { setStrategyRecord(saved); setSettings((current) => ({ ...current, project_id: saved.project_id, strategy_id: saved.id, strategy_version_id: saved.latest_version.id })); setNotice("策略 v1 已保存"); } setDrawer("settings"); } catch (error) { setNotice(`保存失败：${error.message}`); } finally { setSavingStrategy(false); } };
  useEffect(() => { fetch(`${API}/datasets`).then((response) => response.json()).then(setDatasets).catch(() => {}); }, []);
  useEffect(() => { fetch(`${API}/projects/default/strategies`).then((response) => response.json()).then((items) => { const saved = items[0]; if (!saved) return; setStrategyRecord(saved); setSettings((current) => current.strategy_version_id ? current : ({ ...current, project_id: saved.project_id, strategy_id: saved.id, strategy_version_id: saved.latest_version.id, strategy: saved.latest_version.definition })); }).catch(() => {}); }, []);
  useEffect(() => { const controller = new AbortController(); let active = true; Promise.all([fetch(`${API}/securities`, { signal: controller.signal }).then((response) => response.json()), fetch(`${API}/data/status`, { signal: controller.signal }).then((response) => response.json()), fetch(`${API}/backtests?limit=1`, { signal: controller.signal }).then((response) => response.json())]).then(async ([securityData, sourceData, history]) => { if (!active) return; setSecurities(securityData); setSource(sourceData); const latest = history[0]; if (latest?.status === "completed") { setSettings((current) => ({ ...latest.config, project_id: latest.config.project_id || current.project_id, strategy_id: latest.config.strategy_id || current.strategy_id, strategy_version_id: latest.config.strategy_version_id || current.strategy_version_id })); const response = await fetch(`${API}/backtests/${latest.id}/result`, { signal: controller.signal }); if (response.ok && active) { setResult(await response.json()); setProgress(1); } } else { runBacktest(controller.signal); } }).catch((error) => { if (active && error.name !== "AbortError") setSource({ message: "本地服务尚未启动" }); }); return () => { active = false; controller.abort(); }; }, []);
  const metrics = result?.metrics || {};
  const chartData = useMemo(() => (result?.equity_curve || []).filter((_, index, items) => index % Math.max(1, Math.floor(items.length / 240)) === 0), [result]);
  const years = useMemo(() => { const table = {}; for (const item of result?.monthly_returns || []) { table[item.year] ||= {}; table[item.year][item.month] = item.return; } return Object.entries(table).sort(([a], [b]) => Number(b) - Number(a)); }, [result]);
  const openNav = (label) => { if (label === "数据中心") setDrawer("data"); else if (label === "策略研究") setDrawer("strategy"); else if (label === "回测中心" || label === "结果分析") setDrawer("settings"); else setNotice(`${label}将在后续版本开放`); };
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span>QuantLab</span><small>本地量化研究平台</small></div><nav>{navItems.map(([label, Icon]) => <button key={label} className={label === "回测中心" ? "active" : ""} onClick={() => openNav(label)}><Icon size={20} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><span><i />本地服务运行中</span><button onClick={() => setDrawer("settings")}><GearSix size={20} /><span>系统设置</span></button></div></aside>
    <main className="main-view">
      <header className="topbar"><div><h1>数据驾驶舱</h1><p>结果总览与分析</p></div><div className="top-actions"><label><input type="date" value={settings.start_date} onChange={(event) => setSettings({ ...settings, start_date: event.target.value })} /><span>~</span><input type="date" value={settings.end_date} onChange={(event) => setSettings({ ...settings, end_date: event.target.value })} /></label><button className="ghost"><DownloadSimple size={18} />导出报告</button></div></header>
      <div className="workflow">{steps.map((step, index) => <button key={step} className={index === 4 ? "current" : "done"} onClick={() => index === 0 ? setDrawer("data") : index === 1 ? setDrawer("strategy") : setDrawer("settings")}><span>{index + 1}</span><div><b>{step}</b><small>{index === 0 ? `${settings.symbols.length} 只股票 · 日线` : index === 1 ? settings.strategy.name : index === 4 ? "当前步骤" : "已完成"}</small></div>{index < 4 && <i>›</i>}</button>)}</div>
      <section className="report-title"><div><span>回测概览</span><b>{result?.strategy || settings.strategy.name}</b></div><button className="text-button" onClick={runBacktest}><ArrowsClockwise size={17} className={running ? "spin" : ""} />刷新结果</button></section>
      <section className="metrics-strip"><Metric label="累计收益" value={formatPercent(metrics.total_return)} tone={metrics.total_return >= 0 ? "positive" : "negative"} /><Metric label="年化收益" value={formatPercent(metrics.annual_return)} tone={metrics.annual_return >= 0 ? "positive" : "negative"} /><Metric label="最大回撤" value={formatPercent(metrics.max_drawdown)} tone="negative" /><Metric label="夏普比率" value={Number(metrics.sharpe || 0).toFixed(2)} /><Metric label="胜率" value={formatPercent(metrics.win_rate)} /><Metric label="交易次数" value={metrics.trade_count || 0} /></section>
      <section className="chart-panel equity-panel"><div className="panel-head"><div><b>累计净值走势</b><div className="legend"><span className="strategy-line">策略</span><span className="benchmark-line">{result?.benchmark?.label || "沪深300"}</span></div></div><span className="period-badge">{settings.start_date} — {settings.end_date}</span></div><ResponsiveContainer width="100%" height={250}><LineChart data={chartData} margin={{ top: 12, right: 24, left: 4, bottom: 0 }}><CartesianGrid stroke="#243139" vertical={false} /><XAxis dataKey="date" tick={{ fill: "#7f8b91", fontSize: 11 }} tickLine={false} axisLine={false} minTickGap={54} /><YAxis tickFormatter={(value) => `${Math.round(value * 100)}%`} tick={{ fill: "#7f8b91", fontSize: 11 }} tickLine={false} axisLine={false} width={48} /><Tooltip content={<ChartTooltip />} /><Line type="monotone" dataKey="equity" name="策略" stroke="#35c4bd" strokeWidth={2.2} dot={false} isAnimationActive={false} /><Line type="monotone" dataKey="benchmark" name={result?.benchmark?.label || "沪深300"} stroke="#899399" strokeWidth={1.4} dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></section>
      <section className="chart-panel drawdown-panel"><div className="panel-head"><b>最大回撤（回撤区间）</b><span className="negative">{formatPercent(metrics.max_drawdown)}</span></div><ResponsiveContainer width="100%" height={105}><AreaChart data={chartData} margin={{ top: 6, right: 24, left: 4, bottom: 0 }}><CartesianGrid stroke="#243139" vertical={false} /><XAxis dataKey="date" hide /><YAxis tickFormatter={(value) => `${Math.round(value * 100)}%`} tick={{ fill: "#7f8b91", fontSize: 10 }} tickLine={false} axisLine={false} width={48} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="drawdown" name="回撤" stroke="#ef525c" fill="#7d2630" fillOpacity={0.58} isAnimationActive={false} /></AreaChart></ResponsiveContainer></section>
      <section className="lower-grid"><div className="chart-panel heatmap-panel"><div className="panel-head"><b>月度收益热力图（%）</b></div><div className="heatmap"><div className="heat-row heat-head"><span />{Array.from({ length: 12 }, (_, index) => <span key={index}>{index + 1}月</span>)}</div>{years.slice(0, 7).map(([year, values]) => <div className="heat-row" key={year}><b>{year}</b>{Array.from({ length: 12 }, (_, index) => { const value = values[index + 1]; return <span key={index} className={value == null ? "empty" : value >= 0 ? "gain" : "loss"}>{value == null ? "—" : (value * 100).toFixed(1)}</span>; })}</div>)}</div></div><div className="chart-panel trades-panel"><div className="panel-head"><b>交易记录（最近 10 笔）</b><button className="text-button">查看全部 ›</button></div><div className="table-wrap"><table><thead><tr><th>交易日期</th><th>代码</th><th>名称</th><th>方向</th><th>成交价</th><th>数量</th><th>收益</th></tr></thead><tbody>{(result?.trades || []).slice(0, 10).map((trade, index) => <tr key={`${trade.date}-${trade.symbol}-${index}`}><td>{trade.date}</td><td>{trade.symbol}</td><td>{trade.name}</td><td className={trade.side === "买入" ? "negative" : "positive"}>{trade.side}</td><td>{trade.price}</td><td>{formatMoney(trade.quantity)}</td><td className={(trade.pnl || 0) >= 0 ? "positive" : "negative"}>{trade.pnl == null ? "—" : formatMoney(trade.pnl)}</td></tr>)}</tbody></table></div></div></section>
      <footer><span><i />数据状态正常</span><span>数据源：{source?.source || "连接中"}</span><span>引擎版本 v0.3.0</span><span><Info size={16} />回测不代表未来收益</span></footer>
    </main>
    {drawer === "settings" && <SettingsDrawer settings={settings} setSettings={setSettings} onRun={runBacktest} onCancel={cancelBacktest} running={running} progress={progress} close={() => setDrawer(null)} />}{drawer === "strategy" && <StrategyModal settings={settings} setSettings={setSettings} onSave={saveStrategy} saving={savingStrategy} versionInfo={strategyRecord?.latest_version ? `v${strategyRecord.latest_version.version}` : null} close={() => setDrawer("settings")} />}{drawer === "data" && <DataDrawer settings={settings} setSettings={setSettings} securities={securities} source={source} datasets={datasets} onImport={importCsv} importing={importing} close={() => setDrawer("settings")} />}{notice && <button className="toast" onClick={() => setNotice("")}>{notice}<X size={15} /></button>}
  </div>;
}
export { App };
